In [41]:
from pandas import DataFrame

In [42]:
data1 = {'name':['김상순','이순자','강남길'], 
         'addr':['서울','인천','경기'],
         'age':[21,28,24]}
data1

{'name': ['김상순', '이순자', '강남길'],
 'addr': ['서울', '인천', '경기'],
 'age': [21, 28, 24]}

In [43]:
df = DataFrame(data1)
df

  name addr  age
0  김상순   서울   21
1  이순자   인천   28
2  강남길   경기   24

In [44]:
df2 = DataFrame(data1, columns=['name', 'age', 'addr'], index=['no1', 'no2', 'no3'])
df2

    name  age addr
no1  김상순   21   서울
no2  이순자   28   인천
no3  강남길   24   경기

In [45]:
df2.columns

Index(['name', 'age', 'addr'], dtype='str')

In [46]:
df2.index

Index(['no1', 'no2', 'no3'], dtype='str')

In [47]:
df2['name']

no1    김상순
no2    이순자
no3    강남길
Name: name, dtype: str

In [48]:
df2.name

no1    김상순
no2    이순자
no3    강남길
Name: name, dtype: str

In [49]:
df2.loc['no2']  # index를 기준으로 행을 추출
df2.iloc[2]     # 행번호 기준으로 추출

name    강남길
age      24
addr     경기
Name: no3, dtype: object

In [50]:
df2.loc[['no1','no3']]

    name  age addr
no1  김상순   21   서울
no3  강남길   24   경기

In [51]:
df2.loc['no1':'no3']

    name  age addr
no1  김상순   21   서울
no2  이순자   28   인천
no3  강남길   24   경기

In [52]:
df2.iloc[1]
df2.iloc[[0,2]]

    name  age addr
no1  김상순   21   서울
no3  강남길   24   경기

In [53]:
df2.iloc[0:2]

    name  age addr
no1  김상순   21   서울
no2  이순자   28   인천

In [54]:
# 특정 데이터 추출
df2.name['no2']

'이순자'

In [55]:
df2['name']['no2']

'이순자'

In [56]:
# 특정 행과 열 데이터 추출
df2.loc[['no1','no3'],['name','age']]

    name  age
no1  김상순   21
no3  강남길   24

In [57]:
df2.iloc[[0,2],[0,1]]

    name  age
no1  김상순   21
no3  강남길   24

In [58]:
df2.sort_index(ascending=False) # default는 True 오름차순 정렬

    name  age addr
no3  강남길   24   경기
no2  이순자   28   인천
no1  김상순   21   서울

In [59]:
df2.sort_values(by='age', ascending=False)

    name  age addr
no2  이순자   28   인천
no3  강남길   24   경기
no1  김상순   21   서울

In [60]:
df3 = DataFrame({'이원용':{'지역':'서울', 'age':21},
                '박미자':{'지역':'경기', 'age':32},
                '최길동':{'지역':'부산', 'age':27}
                })
df3

    이원용 박미자 최길동
지역   서울  경기  부산
age  21  32  27

In [61]:
# 행 <-> 열 변환
df3.T

     지역 age
이원용  서울  21
박미자  경기  32
최길동  부산  27

In [62]:
df2['gender']=['female','male','male']
df2

    name  age addr  gender
no1  김상순   21   서울  female
no2  이순자   28   인천    male
no3  강남길   24   경기    male

In [63]:
df2['age']=25
df2

    name  age addr  gender
no1  김상순   25   서울  female
no2  이순자   25   인천    male
no3  강남길   25   경기    male

In [64]:
df2['addr']=['충청','경상','전라']
df2

    name  age addr  gender
no1  김상순   25   충청  female
no2  이순자   25   경상    male
no3  강남길   25   전라    male

In [65]:
df2.loc['no2','name']='더조은'
df2

    name  age addr  gender
no1  김상순   25   충청  female
no2  더조은   25   경상    male
no3  강남길   25   전라    male

In [66]:
df2.loc['no4']=['최원영',32,'제주','female']
df2

    name  age addr  gender
no1  김상순   25   충청  female
no2  더조은   25   경상    male
no3  강남길   25   전라    male
no4  최원영   32   제주  female

In [67]:
# 행삭제
df4 = df2.drop(['no2','no3'])
df4

    name  age addr  gender
no1  김상순   25   충청  female
no4  최원영   32   제주  female

In [68]:
df2

    name  age addr  gender
no1  김상순   25   충청  female
no2  더조은   25   경상    male
no3  강남길   25   전라    male
no4  최원영   32   제주  female

In [ ]:
# 열 삭제
# del df2['gender']       # 원본이 바뀜
# df2

df5 = df2.drop(['gender','addr'], axis=1)    # 1 => 열
df5

    name  age
no1  김상순   25
no2  더조은   25
no3  강남길   25
no4  최원영   32

In [73]:
df2

    name  age addr  gender
no1  김상순   25   충청  female
no2  더조은   25   경상    male
no3  강남길   25   전라    male
no4  최원영   32   제주  female

In [74]:
df6 = DataFrame({'addr':['충청','제주','전라'],
                'tel':['042','051','076'],
                'department':['컴퓨터공학','통계학과','디자인학과']
                })
df6

  addr  tel department
0   충청  042      컴퓨터공학
1   제주  051       통계학과
2   전라  076      디자인학과

In [75]:
import pandas as pd

In [ ]:
# on='addr' 이면 addr이 겹치는 것만 합치기
result = pd.merge(df2, df6, on='addr')
result

  name  age addr  gender  tel department
0  김상순   25   충청  female  042      컴퓨터공학
1  강남길   25   전라    male  076      디자인학과
2  최원영   32   제주  female  051       통계학과

In [80]:
result2 = pd.merge(df2, df6, how='left')
result2

  name  age addr  gender  tel department
0  김상순   25   충청  female  042      컴퓨터공학
1  더조은   25   경상    male  NaN        NaN
2  강남길   25   전라    male  076      디자인학과
3  최원영   32   제주  female  051       통계학과

In [81]:
result3 = pd.merge(df2, df6, how='right')
result3

  name  age addr  gender  tel department
0  김상순   25   충청  female  042      컴퓨터공학
1  최원영   32   제주  female  051       통계학과
2  강남길   25   전라    male  076      디자인학과

In [84]:
df7 = DataFrame({'addr':['충청','제주','경기'],
                'tel':['042','051','076'],
                'department':['컴퓨터공학','통계학과','디자인학과']
                })

In [85]:
result4 = pd.merge(df2, df7, how='outer')
result4

  name   age addr  gender  tel department
0  NaN   NaN   경기     NaN  076      디자인학과
1  더조은  25.0   경상    male  NaN        NaN
2  강남길  25.0   전라    male  NaN        NaN
3  최원영  32.0   제주  female  051       통계학과
4  김상순  25.0   충청  female  042      컴퓨터공학

In [86]:
# 데이터 프레임 연결
result5 = pd.concat([df2,df7])
result5

    name   age addr  gender  tel department
no1  김상순  25.0   충청  female  NaN        NaN
no2  더조은  25.0   경상    male  NaN        NaN
no3  강남길  25.0   전라    male  NaN        NaN
no4  최원영  32.0   제주  female  NaN        NaN
0    NaN   NaN   충청     NaN  042      컴퓨터공학
1    NaN   NaN   제주     NaN  051       통계학과
2    NaN   NaN   경기     NaN  076      디자인학과