In [1]:
from pandas import DataFrame
import numpy as np

In [2]:
df1 = DataFrame(np.zeros((3,3), int), index=['one','two','three'])
df1

       0  1  2
one    0  0  0
two    0  0  0
three  0  0  0

In [3]:
df2 = df1 + 3
df2

       0  1  2
one    3  3  3
two    3  3  3
three  3  3  3

In [4]:
df3 = DataFrame(np.ones((4,4), int), index=['one','two','three','four'])
df3

       0  1  2  3
one    1  1  1  1
two    1  1  1  1
three  1  1  1  1
four   1  1  1  1

In [ ]:
# 행이름과 열이름이 일치하는 위치끼리만 계산
df4 = df2 + df3
df4

         0    1    2   3
four   NaN  NaN  NaN NaN
one    4.0  4.0  4.0 NaN
three  4.0  4.0  4.0 NaN
two    4.0  4.0  4.0 NaN

In [6]:
df2.add(df3)

         0    1    2   3
four   NaN  NaN  NaN NaN
one    4.0  4.0  4.0 NaN
three  4.0  4.0  4.0 NaN
two    4.0  4.0  4.0 NaN

In [ ]:
# 없는 값은 0으로 대체 => 0+1이 됨
df2.add(df3, fill_value=0)

         0    1    2    3
four   1.0  1.0  1.0  1.0
one    4.0  4.0  4.0  1.0
three  4.0  4.0  4.0  1.0
two    4.0  4.0  4.0  1.0

In [10]:
df2.add(df3, fill_value=10)

          0     1     2     3
four   11.0  11.0  11.0  11.0
one     4.0   4.0   4.0  11.0
three   4.0   4.0   4.0  11.0
two     4.0   4.0   4.0  11.0