In [1]:
from pandas import DataFrame

In [2]:
df = DataFrame({'거래처':['company1','company2','company3','company4','company5'],
                '주문량':[1500, 1450, 1300, 100, 57],
                '할인율':[0.2, 0.19, 0.15, 0.1, 0.05]
                })
df

        거래처   주문량   할인율
0  company1  1500  0.20
1  company2  1450  0.19
2  company3  1300  0.15
3  company4   100  0.10
4  company5    57  0.05

In [3]:
df.sum()

거래처    company1company2company3company4company5
주문량                                        4407
할인율                                        0.69
dtype: object

In [4]:
df.cumsum()

                                        거래처   주문량   할인율
0                                  company1  1500  0.20
1                          company1company2  2950  0.39
2                  company1company2company3  4250  0.54
3          company1company2company3company4  4350  0.64
4  company1company2company3company4company5  4407  0.69

In [6]:
# numeric_only=True 옵션은 숫자만 평균 내기
df.mean(numeric_only=True)

주문량    881.400
할인율      0.138
dtype: float64

In [7]:
df.describe()

               주문량       할인율
count     5.000000  5.000000
mean    881.400000  0.138000
std     736.786808  0.063008
min      57.000000  0.050000
25%     100.000000  0.100000
50%    1300.000000  0.150000
75%    1450.000000  0.190000
max    1500.000000  0.200000

In [8]:
df.sum(axis=1, numeric_only=True)

0    1500.20
1    1450.19
2    1300.15
3     100.10
4      57.05
dtype: float64

In [9]:
df.sum(1, numeric_only=True)

C:\Users\mega\AppData\Local\Temp\ipykernel_16540\363520233.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  df.sum(1, numeric_only=True)

0    1500.20
1    1450.19
2    1300.15
3     100.10
4      57.05
dtype: float64

In [10]:
df1 = DataFrame({'거래처':['company1','company2','company3','company4','company5','company2','company3'],
                '주문량':[1500, 1450, 1300, 100, 57, 567, 532],
                '할인율':[0.2, 0.19, 0.15, 0.1, 0.05, 0.12, 0.14]
                })
df1

        거래처   주문량   할인율
0  company1  1500  0.20
1  company2  1450  0.19
2  company3  1300  0.15
3  company4   100  0.10
4  company5    57  0.05
5  company2   567  0.12
6  company3   532  0.14

In [11]:
df1.거래처.unique()

<StringArray>
['company1', 'company2', 'company3', 'company4', 'company5']
Length: 5, dtype: str

In [12]:
df1['거래처'].value_counts()

거래처
company2    2
company3    2
company1    1
company4    1
company5    1
Name: count, dtype: int64