In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(np.ones((4,4)), index=['a','b','c','d'])
df

     0    1    2    3
a  1.0  1.0  1.0  1.0
b  1.0  1.0  1.0  1.0
c  1.0  1.0  1.0  1.0
d  1.0  1.0  1.0  1.0

In [5]:
# b행의 1열에 결측치 삽입
df.loc['b', 1] = np.nan
df

df.loc['b':, 3] = np.nan
df

     0    1    2    3
a  1.0  1.0  1.0  1.0
b  1.0  NaN  1.0  NaN
c  1.0  1.0  1.0  NaN
d  1.0  1.0  1.0  NaN

In [6]:
pd.isnull(df)

       0      1      2      3
a  False  False  False  False
b  False   True  False   True
c  False  False  False   True
d  False  False  False   True

In [7]:
pd.notnull(df)

      0      1     2      3
a  True   True  True   True
b  True  False  True  False
c  True   True  True  False
d  True   True  True  False

In [ ]:
# 3열의 True의 합계(count의 의미)
df[3].isnull().sum()

np.int64(3)

In [ ]:
# 한행에 결측치가 하나라도 있으면 제외
df.dropna()

     0    1    2    3
a  1.0  1.0  1.0  1.0

In [ ]:
# 한행이 모두 결측치 일때만 제외
df.dropna(how='all')

     0    1    2    3
a  1.0  1.0  1.0  1.0
b  1.0  NaN  1.0  NaN
c  1.0  1.0  1.0  NaN
d  1.0  1.0  1.0  NaN

In [11]:
# 결측값을 임의의 값으로 대체
df.fillna(0)

     0    1    2    3
a  1.0  1.0  1.0  1.0
b  1.0  0.0  1.0  0.0
c  1.0  1.0  1.0  0.0
d  1.0  1.0  1.0  0.0

In [ ]:
# 1열의 모든 결측치는 5로, 3열의 모든 결측치는 7로 대체
df.fillna({1:5, 3:7})

     0    1    2    3
a  1.0  1.0  1.0  1.0
b  1.0  5.0  1.0  7.0
c  1.0  1.0  1.0  7.0
d  1.0  1.0  1.0  7.0

In [15]:
df.fillna('unknown')

     0        1    2        3
a  1.0      1.0  1.0      1.0
b  1.0  unknown  1.0  unknown
c  1.0      1.0  1.0  unknown
d  1.0      1.0  1.0  unknown