In [1]:
import json

In [2]:
d1 = json.load(open('data/restaurantinfo.json'))
d1

{'kind1': 'koreanfood',
 'region': ['nosong', 'bibim', 'jungsung'],
 'food_name': {'best-of-best': 'bibimbab', 'one-of-best': 'bulgogi'}}

In [3]:
import pandas as pd

In [8]:
df = pd.read_json('data/employees.json')
df

   id name  age department  salary
0   1  홍기영   25        개발팀    3500
1   2  김철수   30       데이터팀    4200
2   3  이영희   28        개발팀    3900
3   4  박민수   35        기획팀    4500
4   5  최수진   27       데이터팀    4100

In [10]:
print(df.shape)
print(df.info())

(5, 5)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5 non-null      int64
 1   name        5 non-null      str
 2   age         5 non-null      int64
 3   department  5 non-null      str
 4   salary      5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes
None

In [15]:
print(df['name'])
print('-'*30)

# 30세 이상   df[조건]
print(df[df['age']>=30])
print('-'*30)

# 개발팀
df[df['department']=='개발팀']

0    홍기영
1    김철수
2    이영희
3    박민수
4    최수진
Name: name, dtype: str
------------------------------
   id name  age department  salary
1   2  김철수   30       데이터팀    4200
3   4  박민수   35        기획팀    4500
------------------------------

   id name  age department  salary
0   1  홍기영   25        개발팀    3500
2   3  이영희   28        개발팀    3900

In [17]:
print(f'급여 평균 : {df['salary'].mean()}')
print(f'급여 합계 : {df['salary'].sum()}')
print(f'급여 최대값 : {df['salary'].max()}')
print(f'급여 최소값 : {df['salary'].min()}')

급여 평균 : 4040.0
급여 합계 : 20200
급여 최대값 : 4500
급여 최소값 : 3500